### PR TITLE
Avoid broken pipe errors when buffer is closed

### PR DESCRIPTION
**Pull request by miried**
When writing to the buffer, gpg can be already closed. One example when this happens is when invoking gpg for encryption but the key does not exist. gpg will exit immediately with exit code 2, but the copy_data thread will still try to write the file to be encrypted to stdin.

Note: This fix does not fully avoid all cases of race conditions, as the check is not truly atomic, but it improves the current situation.

### CODE REVIEW

**Comment by miried** [comment]
During additional testing, I still ran into concurrency problems. I think it needs more testing.

**Comment by vsajip** [comment]
OK - please don't forget to add tests for the specific conditions which your changes are intended to address.

**Comment by vsajip** [comment]
By the way, these errors are currently caught and swallowed, though they do appear in the log. What exactly is the problem to be fixed? For example, if I try to encrypt some data using a non-existent key, I get a return value like this:
```python
{'creation_date': None,
 'data': b'',
 'expire_timestamp': None,
 'fingerprint': None,
 'gpg': <gnupg.GPG object at 0x7f7a0855d8d0>,
 'key_id': None,
 'key_status': None,
 'ok': False,
 'pubkey_fingerprint': None,
 'returncode': 2,
 'sig_info': {},
 'sig_timestamp': None,
 'signature_id': None,
 'status': 'invalid recipient',
 'stderr': 'gpg: BADF00D: skipped: No public key\n'
           '[GNUPG:] INV_RECP 1 BADF00D\n'
           '[GNUPG:] FAILURE encrypt 9\n'
           'gpg: [stdin]: encryption failed: No public key\n',
 'timestamp': None,
 'trust_level': None,
 'trust_text': None,
 'username': None,
 'valid': False}
```
which seems reasonable (reason for failure evident), and while the log does contain
```
893: gpg --status-fd 2 --no-tty --no-verbose --fixed-list-mode --batch --wit
h-colons --homedir keys --encrypt --recipient BADF00D --armor
data copier: <Thread(Thread-3 (_copy_data), initial daemon)>, <_io.BytesIO o
bject at 0x7f7a08542890>, <_io.BufferedWriter name=5>
stderr reader: <Thread(Thread-4 (_read_response), initial daemon)>
stdout reader: <Thread(Thread-5 (_read_data), initial daemon)>
Error sending data
Traceback (most recent call last):
  File "/home/runner/python3-gnupg/venv/lib/python3.10/site-packages/gnupg.p
y", line 155, in _copy_data
    outstream.write(data)
BrokenPipeError: [Errno 32] Broken pipe
gpg: BADF00D: skipped: No public key
Exception occurred while closing: ignored
Traceback (most recent call last):
  File "/home/runner/python3-gnupg/venv/lib/python3.10/site-packages/gnupg.p
y", line 164, in _copy_data
    outstream.close()
BrokenPipeError: [Errno 32] Broken pipe
[GNUPG:] INV_RECP 1 BADF00D
closed output, 70656 bytes sent
[GNUPG:] FAILURE encrypt 9
gpg: [stdin]: encryption failed: No public key
gpg returned a non-zero error code: 2
encrypt result[:100]: b''
```
I don't see why that's a problem.

**Comment by Hamza442** [comment]
@vsajip @miried can this be a fix for issue that I am facing : https://github.com/vsajip/python-gnupg/issues/215#issuecomment-1343098624

**Comment by vsajip** [comment]
Well, @miried hasn't answered my question in [this comment](https://github.com/vsajip/python-gnupg/pull/210#issuecomment-1285908090), and neither have you @Hamza442.

**Comment by Hamza442** [comment]
@vsajip I will be responding got stuck into work

**Comment by vsajip** [comment]
I'll close this as there has been no response or activity for a long while.

**Pull request closed without merging**
