### PR TITLE
scan keys not in a file

### PR DESCRIPTION
**Pull request by skymoore**
Changes:
- add new scan_keys_mem() that takes str or bytes
- add _decode_result(), broken out from _get_list_output()
- test for new scan_keys_mem()

### CODE REVIEW

**Comment by vsajip** [comment]
Hmmm ... I don't want to break existing code for people who are using `scan_keys()`. I would rather add the new functionality as `scan_keys_mem()` - while it may not be as pure, it's more pragmatic.

**Comment by skymoore** [comment]
> Hmmm ... I don't want to break existing code for people who are using `scan_keys()`. I would rather add the new functionality as `scan_keys_mem()` - while it may not be as pure, it's more pragmatic.

@vsajip Makes sense to me.  Updated last commit.

```
test_scan_keys_mem (__main__.GPGTestCase)
Test that external keys in memory can be scanned ... ok
```

**Comment by vsajip** [comment]
I note that the function fails with GnuPG 1.4.x with `NODATA` errors. Any comments on that, @skymoore ?

**Comment by skymoore** [comment]
> I note that the function fails with GnuPG 1.4.x with `NODATA` errors. Any comments on that, @skymoore ?

@vsajip No comments on that.  Not sure why that version range would fail.

**Comment by vsajip** [comment]
It looks like it was an error in the test. You had
```python
for key in (KEYS_TO_IMPORT):
```
which should be
```python
for key in (KEYS_TO_IMPORT,):
```
Now corrected.

**Comment by skymoore** [comment]
> It looks like it was an error in the test. You had
> ```python
> for key in (KEYS_TO_IMPORT):
> ```
> which should be
> ```python
> for key in (KEYS_TO_IMPORT,):
> ```
> Now corrected.

Thank you for the fix and the feedback.

**Pull request merged**
